#TODO: File seems gone.
development:
  adapter: mysql
  database: typo_dev
  host: localhost
  username: root
  password: 

test:
  adapter: mysql
  database: typo_tests
  host: localhost
  username: root
  password: 

production:
  adapter: postgresql
  database: typo
  host: 
  username: typo
  password: 
