development:
  adapter: postgresql
  database: typo
  host: 
  username: typo
  password: 

test:
  adapter: postgresql
  database: typo_tests
  host:
  username: typo
  password: 

production:
  adapter: postgresql
  database: typo
  host: 
  username: typo
  password: 
